import { Link } from 'wouter';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCart } from '@/hooks/use-cart';
import { formatKes } from '@/lib/format';

export default function Cart() {
  const { items, itemCount, subtotal, updateQuantity, removeItem } = useCart();
  if (!items.length) return <section className="cart-page cart-page-empty"><p className="quiet-label">Your bag / 0 items</p><ShoppingBag className="cart-empty-icon" /><h1>Made to be carried.</h1><p>Explore iLonito bags and accessories, handmade in Kenya to move with your life.</p><Link className="pill-button" href="/shop">Explore the collection <ArrowRight size={15} /></Link></section>;
  return <section className="cart-page"><div className="cart-page-heading"><div><p className="quiet-label">Your bag / {itemCount} {itemCount === 1 ? 'item' : 'items'}</p><h1>Take your time.</h1></div><Link href="/shop">Continue shopping</Link></div><div className="cart-page-layout"><div className="cart-page-lines">{items.map(({ product, quantity }) => <article key={product.id}><Link href={`/product/${product.id}`}><img src={product.imageUrl} alt={product.name} /></Link><div><span>{product.category}</span><h2>{product.name}</h2><strong>{formatKes(product.price)}</strong><button className="cart-page-remove" onClick={() => removeItem(product.id)}><Trash2 size={12} /> Remove</button></div><div className="cart-page-controls"><strong>{formatKes(product.price * quantity)}</strong><div className="cart-quantity"><button onClick={() => updateQuantity(product.id, quantity - 1)} aria-label={`Decrease ${product.name}`}><Minus size={12} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} aria-label={`Increase ${product.name}`}><Plus size={12} /></button></div></div></article>)}</div><aside className="cart-page-summary"><p className="quiet-label">Order summary</p><div><span>Subtotal</span><strong>{formatKes(subtotal)}</strong></div><div><span>Delivery</span><strong>Arranged after order</strong></div><hr /><div><span>Total</span><strong>{formatKes(subtotal)}</strong></div><p>International shipping is quoted after ordering.</p><Link href="/checkout" className="pill-button">Continue to checkout <ArrowRight size={15} /></Link></aside></div></section>;
}